// WS5 Task 5.7 (placeholder until pipeline runs) — Bushy chat harness
// PERSONA_L1: per-topic ~800-token chunks synthesized from the personality
// books. Each topic pulls primarily from the authors that teach it best
// (see design doc §5 table).
//
// This file is generated by `scripts/distill-persona/06-emit.ts`. Running
// `npm run distill-persona -- --all` overwrites this file with the actual
// per-topic content.
//
// Until the pipeline runs, each topic maps to an empty string — the
// composer filters out empties before joining, so the system prompt is
// still valid.

import type { PersonaTopic } from "./persona-l0";

export const PERSONA_L1: Record<PersonaTopic, string> = {
  opening_a_conversation: "",
  gathering_information: "",
  building_rapport: "",
  handling_disagreement: "",
  delivering_hard_advice: "",
  silence_and_pacing: "",
  negotiating_data_share: "",
};

export type { PersonaTopic };
