// WS5 Task 5.5 (placeholder until pipeline runs) — Bushy chat harness
// PERSONA_L0: ~500-token unified persona card synthesized from all 7 topic
// chunks via the distillation pipeline (scripts/distill-persona.ts).
//
// This file is generated by `scripts/distill-persona/06-emit.ts`. Running
// `npm run distill-persona -- --all` overwrites this file with the
// Sonnet-synthesized + Opus-verified L0 card.
//
// Until the pipeline runs, this stub keeps the system-prompt composer
// compilable. The voice kernel (voice-kernel.ts) provides the baseline
// identity anchor — without L0 the system prompt is still functional,
// just thinner.

export type PersonaTopic =
  | "opening_a_conversation"
  | "gathering_information"
  | "building_rapport"
  | "handling_disagreement"
  | "delivering_hard_advice"
  | "silence_and_pacing"
  | "negotiating_data_share";

export const PERSONA_L0 = "";

/**
 * Sentinel for the composer — lets it detect whether the pipeline has run
 * and emit a log warning if L0 is still empty. The harness keeps working
 * without L0; it just has less persona scaffolding.
 */
export const PERSONA_L0_IS_PIPELINE_FILLED = PERSONA_L0.length > 0;
