-- Canada provincial seeding progress, starting with Manitoba's first 2026 crop report.
-- This is public source data; writes stay service-role/postgres only.

create table if not exists public.canada_seeding_progress (
  id bigint generated by default as identity primary key,
  province_code text not null,
  province_name text not null,
  crop_year smallint not null,
  report_date date not null,
  report_label text not null,
  source_name text not null,
  source_url text not null,
  seeded_pct numeric(5, 2),
  seeded_pct_previous_year numeric(5, 2),
  seeded_pct_5yr_avg numeric(5, 2),
  seeded_pct_vs_5yr_avg numeric(5, 2),
  status text not null default 'reported',
  summary text not null,
  regional_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint canada_seeding_progress_province_code_check
    check (province_code in ('AB', 'SK', 'MB')),
  constraint canada_seeding_progress_status_check
    check (status in ('reported', 'scheduled', 'not_released')),
  constraint canada_seeding_progress_pct_check
    check (
      (seeded_pct is null or (seeded_pct >= 0 and seeded_pct <= 100))
      and (seeded_pct_previous_year is null or (seeded_pct_previous_year >= 0 and seeded_pct_previous_year <= 100))
      and (seeded_pct_5yr_avg is null or (seeded_pct_5yr_avg >= 0 and seeded_pct_5yr_avg <= 100))
    ),
  constraint canada_seeding_progress_unique_report
    unique (province_code, crop_year, report_date)
);

alter table public.canada_seeding_progress enable row level security;

revoke insert, update, delete, truncate
on public.canada_seeding_progress
from anon, authenticated;

grant select
on public.canada_seeding_progress
to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'canada_seeding_progress'
      and policyname = 'Anon can read Canada seeding progress'
  ) then
    create policy "Anon can read Canada seeding progress"
      on public.canada_seeding_progress
      for select
      to anon
      using (true);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'canada_seeding_progress'
      and policyname = 'Authenticated users can read Canada seeding progress'
  ) then
    create policy "Authenticated users can read Canada seeding progress"
      on public.canada_seeding_progress
      for select
      to authenticated
      using (true);
  end if;
end $$;

insert into public.canada_seeding_progress (
  province_code,
  province_name,
  crop_year,
  report_date,
  report_label,
  source_name,
  source_url,
  seeded_pct,
  seeded_pct_previous_year,
  seeded_pct_5yr_avg,
  seeded_pct_vs_5yr_avg,
  status,
  summary,
  regional_notes
) values (
  'MB',
  'Manitoba',
  2026,
  '2026-05-05',
  'Crop Report - May 5, 2026',
  'Manitoba Agriculture Crop Report',
  'https://www.gov.mb.ca/agriculture/crops/seasonal-reports/crop-report/pubs/crop-report-2026-05-05.pdf',
  2,
  8,
  6,
  -4,
  'reported',
  'Province-wide seeding completion is 2%. The report notes spring wheat and corn starting in Central and Eastern regions, field peas starting in Southwest and Central regions, and no oilseeds planted yet.',
  '[
    {"region":"Southwest","note":"Seeding began in some areas; approximately 2% complete overall."},
    {"region":"Northwest","note":"Field operations have not begun; soils remain saturated in parts of the region."},
    {"region":"Central","note":"Spring wheat, peas, and corn seeding is underway on suitable fields."},
    {"region":"Eastern","note":"Spring wheat is estimated at 5% planted; corn is estimated at 1-2% planted."},
    {"region":"Interlake","note":"General seeding has not commenced; limited starts in drier areas near Woodlands."}
  ]'::jsonb
)
on conflict (province_code, crop_year, report_date) do update
set
  report_label = excluded.report_label,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  seeded_pct = excluded.seeded_pct,
  seeded_pct_previous_year = excluded.seeded_pct_previous_year,
  seeded_pct_5yr_avg = excluded.seeded_pct_5yr_avg,
  seeded_pct_vs_5yr_avg = excluded.seeded_pct_vs_5yr_avg,
  status = excluded.status,
  summary = excluded.summary,
  regional_notes = excluded.regional_notes,
  updated_at = now();
