-- Canada provincial crop progress observations.
--
-- This table is intentionally source-facing: it stores crop/report/region facts
-- that can feed both the seeding map and the bullish/bearish thesis packet.

create table if not exists public.canada_crop_progress (
  id bigint generated by default as identity primary key,
  source_run_id uuid references public.source_runs(id) on delete set null,
  province_code text not null,
  province_name text not null,
  crop_year smallint not null,
  report_date date not null,
  release_date date,
  period_start date,
  period_end date,
  report_label text not null,
  source_name text not null,
  source_url text not null,
  document_url text,
  region_scope text not null,
  region_code text not null,
  region_name text not null,
  crop_name text not null,
  canonical_grain text,
  metric text not null,
  value_pct numeric(6, 2),
  previous_year_pct numeric(6, 2),
  five_year_avg_pct numeric(6, 2),
  unit text not null default 'percent',
  source_excerpt text,
  confidence text not null default 'high',
  quality_flags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint canada_crop_progress_province_code_check
    check (province_code in ('AB', 'SK', 'MB')),
  constraint canada_crop_progress_region_scope_check
    check (region_scope in ('province', 'crop_region')),
  constraint canada_crop_progress_metric_check
    check (
      metric in (
        'seeded_pct',
        'emerged_pct',
        'harvested_pct',
        'condition_good_excellent_pct',
        'pasture_good_excellent_pct',
        'soil_moisture_adequate_surplus_pct'
      )
    ),
  constraint canada_crop_progress_pct_check
    check (
      (value_pct is null or (value_pct >= 0 and value_pct <= 100))
      and (previous_year_pct is null or (previous_year_pct >= 0 and previous_year_pct <= 100))
      and (five_year_avg_pct is null or (five_year_avg_pct >= 0 and five_year_avg_pct <= 100))
    ),
  constraint canada_crop_progress_confidence_check
    check (confidence in ('high', 'medium', 'low')),
  constraint canada_crop_progress_unique_observation
    unique (
      province_code,
      crop_year,
      report_date,
      region_scope,
      region_code,
      crop_name,
      metric
    )
);

create index if not exists idx_canada_crop_progress_latest
  on public.canada_crop_progress (
    crop_year,
    province_code,
    crop_name,
    metric,
    report_date desc
  );

create index if not exists idx_canada_crop_progress_canonical
  on public.canada_crop_progress (
    crop_year,
    canonical_grain,
    metric,
    report_date desc
  )
  where canonical_grain is not null;

alter table public.canada_crop_progress enable row level security;

revoke insert, update, delete, truncate
on public.canada_crop_progress
from anon, authenticated;

grant select
on public.canada_crop_progress
to anon, authenticated;

drop policy if exists "Anon can read Canada crop progress" on public.canada_crop_progress;
create policy "Anon can read Canada crop progress"
  on public.canada_crop_progress
  for select
  to anon
  using (true);

drop policy if exists "Authenticated users can read Canada crop progress" on public.canada_crop_progress;
create policy "Authenticated users can read Canada crop progress"
  on public.canada_crop_progress
  for select
  to authenticated
  using (true);

create or replace view public.v_canada_crop_progress_latest as
select distinct on (
  province_code,
  region_scope,
  region_code,
  crop_name,
  metric
)
  id,
  source_run_id,
  province_code,
  province_name,
  crop_year,
  report_date,
  release_date,
  period_start,
  period_end,
  report_label,
  source_name,
  source_url,
  document_url,
  region_scope,
  region_code,
  region_name,
  crop_name,
  canonical_grain,
  metric,
  value_pct,
  previous_year_pct,
  five_year_avg_pct,
  case
    when value_pct is not null and previous_year_pct is not null
      then round(value_pct - previous_year_pct, 2)
    else null
  end as value_vs_previous_year_pct,
  case
    when value_pct is not null and five_year_avg_pct is not null
      then round(value_pct - five_year_avg_pct, 2)
    else null
  end as value_vs_five_year_avg_pct,
  unit,
  source_excerpt,
  confidence,
  quality_flags,
  updated_at
from public.canada_crop_progress
order by
  province_code,
  region_scope,
  region_code,
  crop_name,
  metric,
  report_date desc,
  updated_at desc;

grant select on public.v_canada_crop_progress_latest to anon, authenticated;

comment on table public.canada_crop_progress is
  'Official provincial crop progress facts for Canada. Stores report-level seeded/condition observations by province, crop, and region for map and thesis use.';

comment on view public.v_canada_crop_progress_latest is
  'Latest Canada crop-progress observation per province, region, crop, and metric, with derived previous-year and five-year-average deltas.';

notify pgrst, 'reload schema';
